[package]
name = "node_backend"
version = "0.1.1"
edition = "2021"
description = "A cli for creating backend in structured way using node js"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
